server:
  port: 5000
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/playground"
    password: "mysqladmin"
    username: "mysqladmin"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

aspect-package: "com.demo.*.*"
